### ISSUE TITLE
Working with multiple authorities in one SPA.

### ISSUE THREAD

**Issue by azimiester** [maxmantz/redux-oidc#118]
Great work on the library. It works great with one authority for OIDC. Now I want to include another inside the same SPA, I am not sure if it is even possible. 

The usecase is we have multiple auth services one for normal users and the other for admins, I am thinking about using multiple UserManager, oidcMiddleware and Provider but since we have just one oidcReducer, I am not sure if it will work. 

Any guidance with how it can be done will be highly appreciated.

**Comment by maxmantz** [comment]
Interesting scenario. Sadly I haven't had a similar scenario yet, but I'm curious as to how this would work. So let's try it out!

The usual way to go about this would be to still use the same auth provider, but using different scopes for users, admins, etc. I strongly recommend using this approach. I cannot see it working with the reducer provided by this library because they listen to the same actions and don't differentiate between admin or user priviledges. You can always write your own middleware where you check the user data for admins or normal users and dispatch a follow up action to get the data to the correct reducers, which you will also have to implement yourself. 

This is what I can come up with from the top of my head. I hope this can help you out.

**Comment by azimiester** [comment]
Thanks for the prompt reply @maxmantz , I unfortunately have very little control over how things are done from the backend,. 

I have fixed it by using different userManager altogether based on whether the user is admin or a normal user. In our case we didn't have to allow a user to be logged in both as an admin and a user at the same time so it works so far so good.

**Comment by maxmantz** [comment]
Happy to hear it. Feel free to comment should you run into any other problems.
