### ISSUE TITLE
No versions beyond 3.0.0-beta.17 seem to work on deployed environments 

### ISSUE THREAD

**Issue by barrymichaeldoyle** [maxmantz/redux-oidc#121]
I've been using this package for my project the whole year and every now and then I try to refactor my auth in a way to work with the latest version of `redux-oidc` but I always run into the same problem.

My app works fine locally, but my deployments seem to fail on any version after `3.0.0-beta.17` i.e. `3.0.0`, `3.0.1` and `3.0.2` don't work on deployed versions of my application.

The problem is that the the user constantly expires and then immediately it tries to log in again and the user expires again immediately so it just goes in an endless loop.

The frustrating thing is it is extremely difficult to test since it works as it should just fine locally but when it gets deployed it stops working.

Any idea on what could be causing this issue?

**Comment by maxmantz** [comment]
I've upgrade one of my project to the latest versions. And I'm experiencing the same issue. Here is what I found out:

- the problem only affects deployment environments - accessing an OIDC server on another domain, development works fine,
- the problem occurs whether the code is minified or not,
- redux-oidc version is not affecting this - I've tried with `3.0.0-beta.17`, `3.0.0`, `3.0.1` & 3.0.2,
- I've used `oidc-client@1.5.2`.

I'll see if I can find some info on the github page of `oidc-client`. My guess is that the root of the issue lies there.

**Comment by maxmantz** [comment]
@barrymichaeldoyle I've narrowed down the reason for this error on the server side. I also upgraded my backend to `netcoreapp2.1`. In doing so, the migration guide suggests using a cookie policy in `Startup.cs` which caused this behavior. Do you maybe have the same issue?

**Comment by barrymichaeldoyle** [comment]
Possibly, I'm on the front end team so don't work on the back end code. I'll check with the guys on that side.

**Comment by barrymichaeldoyle** [comment]
Thanks @maxmantz!!! Got it all working. I really appreciate the effort you put into testing this all out and getting me on the right track :1st_place_medal:
