### ISSUE TITLE
Need a auto-logout functionality for a React-App

### ISSUE THREAD

**Issue by heeropunjabi** [maxmantz/redux-oidc#128]
Hi @maxmantz,
you are doing pretty amazing work on redux-oidc library.

I have one doubt regarding how to do  **UserManager.signoutRedirect();** when user is idle for more than let's say 30 min. Kind of auto-logout functionality.

Can you please provide some pointer on the same.

Regards,
Heero

**Comment by umerfaruk** [comment]
The question sounds to me something outside the scope of this library. It is more likely to get an answer when posted to general JS forums.

However, you can always track mouse move or key presses and reset a timeout. After the timeout, you can do whatever you like to do.  Something like this https://stackoverflow.com/a/4029518 might help.

**Comment by maxmantz** [comment]
Hi @heeropunjabi and sorry for the late reply. As @umerfaruk rightly pointed out, this is beyond the scope of this library, since the implementation is going to rely heavily upon your circumstances.

As far as the redux part of it goes, you can always implement your own version of an auto-logout and use the action constants this library is using to implement the desired behavior.
