### ISSUE TITLE
Questions about Silent Renewal

### ISSUE THREAD

**Issue by hai-nguyen1112** [maxmantz/redux-oidc#155]
First of all, thank you so much for this library. Wonderful work!

I have some questions about Silent Renewal for Implicit Flow:

1) How long is the default lifetime of the id token?
2) Can we configure the id token lifetime?
3) Can we configure so that auto silent renewal only triggered when the user is active? When the user is inactive, auto silent renewal should not be triggered.

Many thanks

**Comment by maxmantz** [comment]
Hi and many thanks for the kind words.

About your questions:

1. The token lifetime is dependent on the token server, not the client. You won't find any configuration options for that here, since this is a library for the client.
2. This depends on whether or not you have control about the configuration of the token server.
3. This is an interesting question I don't know the answer to. Please direct any questions about this to the maintainer of [oidc-client](https://github.com/IdentityModel/oidc-client-js).

Kind regards
