### ISSUE TITLE
Can redux-oidc be used without react-router-redux

### ISSUE THREAD

**Issue by theirishpenguin** [maxmantz/redux-oidc#17]
Hi,

I'm using React Router 4 and AFIAK there is no version of react-router-redux that works well with RR4. Can redux-oidc be used without react-router-redux? I have got the user signin redirect working but will the middleware that is injected by redux-oidc work? I presume not?

**Comment by maxmantz** [comment]
Yes this package is designed to be independent from routing libraries. I've used react-router-redux in my example because it is the most common but any other routing library should work just the same. The middleware only dispatches redux actions defined in this package, so there are no external dependencies. 

Feel free to use react router 4. I haven't yet used it personally but I'm sure it will work. If you have any further questions you can always ask here :)

**Comment by theirishpenguin** [comment]
Fantastic. Thanks for the quick reply @maxmantz. Looking for to trying this
out!

**Comment by maxmantz** [comment]
Excellent. I'll close this for now. You can always contact me when you need help.

**Comment by theirishpenguin** [comment]
Great! Thanks a mill.
