### ISSUE TITLE
Request: Better error handling or more granularity in auth status

### ISSUE THREAD

**Issue by jbuck79** [maxmantz/redux-oidc#27]
In my app, I'm trying to show a fatal error message when the OAuth server is down. I can't seem to find a way to do this. The middleware logs the error in the console, but I can't seem to catch it. Maybe consider adding an error property to the state or dispatch an error action of some kind?

I would think that the user property being null and isLoadingUser being false would mean that something has gone wrong, but there are brief moments when that state exists but nothing is wrong.

Maybe isLoadingUser should initially be true and only go to false once the user has been found or an error has occurred? Then `user == null && isLoadingUser == false` would mean that something is wrong.

Am I totally off base here? Do I need to just write my own method to ping the OAuth server and make sure it's accessible?

**Comment by maxmantz** [comment]
I don't quite follow you here. It is perfectly fine for the user to be null and isLoadingUser to be false. This just says that no user is currently logged in and doesn't in itself suggest that something has gone wrong. When the auth server is down, redirection on a login attempt would fail visibly, as in you get an error in the browser during redirection. Since the auth server is completely separated from the app itself, it is hard to check for this until you run into it,

You could implement something yourself by manually pinging the auth server before redirection occurs to dispatch some kind of error into your reducer when it returns 404 or 500. However I don't think that this is a requirement for this library.

**Comment by jbuck79** [comment]
I get what you're saying, my issue probably is more due to my unique specs than any drawbacks with this library.

In my app, I don't have a login screen. My app is being integrated into another code-base and the login is done in the other code-base. So when you enter the home page of my app, I dispatch a random action right away to get the middleware started. When everything is working, it'll hit the OAuth server and redirect to the callback page, which then redirects back to the previous page. But when my OAuth server is down, it just sits on the homepage of my app with actions that try and ultimately fail to make requests to my API. The only indication I have that anything has gone wrong (other than my API methods failing) is an error in the console saying that the connection to my OAuth server was rejected.

But I suppose I can handle this by either writing a method to ping the server or just wait for my API call to fail and check the status code.

Thanks for your input!

**Comment by maxmantz** [comment]
No problem. I'll close this for now.
