### ISSUE TITLE
Removal of option 'triggerAuthFlow'

### ISSUE THREAD

**Issue by ErwinSteffens** [maxmantz/redux-oidc#34]
Hi there,

We like to use the `triggerAuthFlow`, but we saw it was removed in v3. Can you elaborate a little bit more on why it was removed?

Is there a simple way of implementing this for ourself?

**Comment by maxmantz** [comment]
I've removed this option because by nature, the OIDC authentication flow suspends the app by navigating to another site. This has potentially drastic consequences for the way the app works and I felt it should not be triggered automatically via a middleware. Instead the developer should be aware, if and when the authentication process is triggered, so that he can take the necessary precautions, such as persisting state, trigger custom actions or do other things if they are required. 

The authentication flow can be triggered quite simply via a function call on the `userManager`. [This](https://github.com/maxmantz/redux-oidc-example/blob/master/src/components/loginPage/index.js#L7) is how it works in the example app.

I hope this answers your question.

**Comment by ErwinSteffens** [comment]
We have our own identity server for logging in users and in our flow the user should always has to login. 

Maybe we can add add callback to specific routes for checking this user login and do the redirecting when needed. We need to allow the callback routes when not logged in.

Thanks for your quick anwser.

**Comment by maxmantz** [comment]
The use case you describe is similar to how the example app is implemented. There, the user is also required to be logged in and the login screen is displayed when no valid authentication is present. I've implemented it in a simple way in the app's [home page](https://github.com/maxmantz/redux-oidc-example/blob/master/src/components/homePage/index.js#L16). Maybe this approach is useful for you too?

**Comment by ErwinSteffens** [comment]
We do not want the user to press the login button, but just open the login screen directly when there is no valid login available. The example app is very useful, I think we will find a solution.

**Comment by Gurkenschreck** [comment]
And if redux-oidc would call a callback function instead of triggering the oidc-client redirection itself?

The user of this lib could (when he wants) register the authFlowCallback while creating the middleware.

**Comment by maxmantz** [comment]
@Gurkenschreck This is an interesting proposition, but i still believe that the middleware is the wrong place for this. 

In fact, I'm thinking about dropping the middleware altogether before v3 leaves beta. The reason I made it was to support `triggerAuthFlow` in previous versions and to load the user data from the `userManager` when the app first loads. This however can be done via a new helper function instead of a middleware. Right now, the middleware serves little purpose other than checking the validity of the user object stored in state at every dispatch.

For your usage scenario, you can listen to the `USER_EXPIRING` & `USER_EXPIRED` actions. Those actions are dispatched via event listeners registered in the [OidcProvider](https://github.com/maxmantz/redux-oidc/blob/master/src/OidcProvider.js#L19). Then you can use your thunks, sagas or other custom actions to   trigger the auth flow (via a helper function I will provide in the future, should the middleware get removed). This however is only required if you're not using silent renew. If you are using silent renew, the token will get refreshed automatically.

**Comment by Gurkenschreck** [comment]
So are you going to drop this module? What is your plan?

**Comment by maxmantz** [comment]
No I'm not going to drop anything. I was thinking about dropping the middleware only for said reasons. But silent renew isn't something that everyone implements, therefore it will remain. No worries.

**Comment by maxmantz** [comment]
I'll close this for now. Feel free to keep posting here if you have additional questions regarding this topic.

**Comment by ErwinSteffens** [comment]
Fixed it by using sagas. Thanks.

**Comment by ErwinSteffens** [comment]
We have some issues with this solution. 

We are re-directing to our auth server now in a saga on the USER_EXPIRED action, but the USER_EXPIRED event is also fired when the initial user loading from local storage fails. So when we are re-directed to the callback page the USER_EXPIRED action is fired before the callback route can be handled and the application redirects the user back to the identity server.

Do you have any suggestions on how to fix this?

Maybe we can introduce a new action that says USER_LOADING_FAILED which tells that initial loading from storage fails so we can differ from the USER_EXPIRED action.

**Comment by maxmantz** [comment]
@ErwinSteffens I have experimented with the LOAD_USER_FAILED action. The question I'm asking myself right now is what kind of effect this should have on the reducers. 

The two options are:
- clear the user from the reducer,
- do nothing.

I'd prefer to do nothing because it doesn't indicate anything is wrong with the stored user, only with the retrieval of a new user object. What are your thoughts on this?

**Comment by ErwinSteffens** [comment]
I had the same idea about introducing a `LOAD_USER_FAILED` action, but I think it does not help us. This new action indicates that there is no valid user stored. So in our case we still need to re-direct the user on this action. 

The problem is that when we are handling the callback this action still happens before the callback handler handles the id_token en stores the user.

**Comment by maxmantz** [comment]
I don't quite follow you. Doesn't this indicate an issue with your `successCallback` insinde the `<CallbackComponent/>`? The new action isn't intended to signalize that no user is stored - just that something went wrong while loading it.

**Comment by ErwinSteffens** [comment]
What we want is that when the user opens the app and when there is no valid user account he is automatically redirected to the login page. I thought this is what the `triggerAuthFlow` in the previous version was ment for. 

In a post above you mentioned: 

> For your usage scenario, you can listen to the USER_EXPIRING & USER_EXPIRED actions. Those actions are dispatched via event listeners registered in the OidcProvider. Then you can use your thunks, sagas or other custom actions to trigger the auth flow (via a helper function I will provide in the future, should the middleware get removed).

So what we now do is call the `signinRedirect()` in a saga on `USER_EXPIRED` action. The problem is that this action is also fired when the app is openend for handling the callback. 

These are the steps that happen:

1. User opens the App on `/app`
2. `redux-oidc` loads the user, but there is no user resulting in `USER_EXPIRED` action
3. Our saga re-directs user to login page on auth server
4. User fills in credentials and gets re-directed back to the app on `/app/callback`
5. `redux-oidc` loads the user, but there is no user resulting in `USER_EXPIRED` action
6. Our saga re-directs user to login page on auth server
7. ~~Callback handles token and stores the user~~

So step 7 does not happen because step 6 already re-directs the user. We can replace the `USER_EXPIRED` with something like `LOAD_USER_FAILED` but I think this does not solve the problem because we still need to re-direct the user to the login page when there is no valid login based on this new action.
