### ISSUE TITLE
Explicitly handling silent renew

### ISSUE THREAD

**Issue by theirishpenguin** [maxmantz/redux-oidc#43]
Hi @maxmantz - again, great library! I am having a problem with the 2.2.1 version of your library, which is probably just my lack of knowledge.

When an API returns me a 401 I want to handle this by performing an explicit silent renew as per this comment https://github.com/IdentityModel/oidc-client-js/issues/298#issuecomment-289790941

_Note: I have auto silent renew working perfectly - it redirects to login page when silent renew fails if you have logged out from the OP server (due to SILENT_RENEW_ERROR being handled by redux-oidc I presume). In my silent_renew.jsx file I simply import the userManager and call `userManager.signinSilentCallback();`_

However, the explicit silent renew is not going so well. When I receive the 401 in javascript (and I am logged out of the OP server) I call `userManager.signinSilent()` but from looking at redux tools it doesn't dispatch a SILENT_RENEW_ERROR.

I tried this as an experiment...

        let theUserManager = userManager;

        userManager.signinSilent().then(user => {
                // This doesn't seem to make any difference when I am logged into the OP Server                                                                                    
                theUserManager.signinSilentCallback();
          }, err => {
            // This seems to cause the SILENT_RENEW_ERROR to be dispatched
            theUserManager.events._raiseSilentRenewError(err);                                      
          });

I'm not sure if I should have to do this manual wiring up? Even when I do I find that the reducer at https://github.com/maxmantz/redux-oidc/blob/v2.2.1/src/reducer/reducer.js#L20 isn't clearing out the user in the redux state. I'm just speculating, but I wonder if the problem is that the userManager instance is different from the instance created and hence somehow wouldn't have a reducer listening to the SILENT_RENEW_ERROR. I've been tearing my hair out trying to solve this. If you've any advice I'd greatly appreciate it.

**Comment by maxmantz** [comment]
Hello again @theirishpenguin and thank you for your kind words!
This is an interesting screnario you're proposing. Usually the `userManager` instance which is processing the default silent renew is communicating effectively with the default userManager, which is why the renewed user object is stored in the redux state after a silent renew occurs.

I must admit that I personally haven't used the userManager's `signinSilent()` function yet, because it is called automatically whenever the user is expiring and silent renew is configured and a 401 doesn't necessarily mean an invalid authentication, but can also mean insufficient permissions during authorization. Maybe the question on how to handle this correctly is best asked at oidc-client's repo?

The reason for `SILENT_RENEW_ERROR` to be dispatched is [the OidcProvider](https://github.com/maxmantz/redux-oidc/blob/master/src/OidcProvider.js#L19). This is the expected behavior. 

The reason why the reducer doesn't clear the user object on a silent renew error is, that the user object might still be valid. I will however contemplate removing the user object if desired.

**Comment by theirishpenguin** [comment]
Thanks for the reply @maxmantz. I will try a few things based on what you have said. Just one question - you say ,"401 doesn't necessarily mean an invalid authentication, but can also mean insufficient permissions during authorization."

However if the user has insufficient permissions during authorization would it not mean a 403 (forbidden) would be returned? I have not checked what that OIDC spec says on this but that's what I would expect from any reasonable web service/REST endpoint, etc.

**Comment by maxmantz** [comment]
What is returned depends on your REST endpoints. It is certainly sensible to implement it that way.

**Comment by theirishpenguin** [comment]
Just a quick update @maxmantz. I think everything works fine with the approach I posted above. Your redux actions are getting triggered in the happy and error code paths. From my testing there is no need to call signinSilentCallback(), nor is there any need to create a **the**UserManager reference to userManager. So the code becomes...

    userManager.signinSilent().then(user => {
        // Nothing to do, handled by oidc-client-js internally
        }, err => {
            userManager.events._raiseSilentRenewError(err);                                      
      });

I'm basically mimicing the way oidc-client-js calls signinSilent within there silentRenew service 
https://github.com/IdentityModel/oidc-client-js/blob/920d484fc37beed8bf25adc7db4f450fae086d01/src/SilentRenewService.js#L21

So you can close this issue. Right now, I'm happy enough that the reducer doesn't clear the user object on a silent renew error - but I'd be okay with you changing that behaviour in future too.

Thanks again! I'm sure I'll be back with more questions soon 😄

**Comment by maxmantz** [comment]
Happy to hear that!
