### ISSUE TITLE
signinRedirect leaves me in a loop

### ISSUE THREAD

**Issue by YellowSmiley** [maxmantz/redux-oidc#57]
We have an issue as seen below. The component's `this.props.user` is null, so the `userManager.signinRedirect();` is called, the store updates, the page is refreshed and thus the store loses it's value. It goes through the below check again and because `this.props.user` is null again, it gets stuck in a loop.
```
if (!this.props.user) {
  userManager.signinRedirect();
}
```
In your example you use:
```
function HomePage(props) {
  const { user } = props;

  return !user || user.expired ? <LoginPage/> : <MainPage />;
}
```
... and LoginPage then handles the signinRedirect and the app routes to MainPage. What am I doing wrong? Is it even possible to do it the way I'm doing it? How are you maintaining the store?

**Comment by maxmantz** [comment]
Hi and thanks for your question. As you've already hinted at, your approach is not working because it never hits the callback page where the `<CallbackComponent />` is mounted. Only after this happens, the user is loaded into the store, so this happens before your check to `!this.props.user`. 

When reloading the page, there is a helper function called `loadUser`, which takes in the userManager and redux-store and loads the user from existing data. If the current user object is still valid, this then gets loaded into the store. I've used it when I [create the store](https://github.com/maxmantz/redux-oidc-example/blob/master/src/store.js#L30) in the example app.

Hope this helps!

**Comment by YellowSmiley** [comment]
That confirms our theory. Thanks! We were hoping we could rid ourselves of the login home and routes pages but with them, it works; so they'll have to stay!
