### ISSUE TITLE
Best practice for testing with redux-oidc?

### ISSUE THREAD

**Issue by nmenglund** [maxmantz/redux-oidc#71]
Thanks for a very useful library. It's working great for authentication, but after installing it, it keeps the project tests from running: I get missing references to `sessionStorage` and `localStorage` (for wholly unrelated tests). How should I set up my project to avoid the tests failing? Could you add a simple test to the example project? (keeping the same code path on client/server as much as possible)

**Comment by NerdySaiyan** [comment]
sessionStorage and localStorage are available in a web environment, but not in a node environment. The problem here is really in oidc-client which is interacting with those dependencies. The oidc-client library does provide WebStorageStateStore and InMemoryWebStorage which you can use in a non-browser environment. I recommend you swap the InMemoryWebStorage in place of sessionStorage and localStorage when in a 'test' environment.

```
import { createUserManager } from 'redux-oidc';
import { WebStorageStateStore, InMemoryWebStorage } from 'oidc-client';

const userManagerConfig = {
...
};

if (process.env.NODE_ENV === 'test') {
  const stateStoreStorage = new InMemoryWebStorage();
  const userStoreStorage = new InMemoryWebStorage();

  userManagerConfig.stateStore = new WebStorageStateStore({ store: stateStoreStorage });
  userManagerConfig.userStore = new WebStorageStateStore({ store: userStoreStorage });
}

const userManager = createUserManager(userManagerConfig);
```

**Comment by maxmantz** [comment]
Thank you @NerdySaiyan. Great answer!

**Comment by anto-pt** [comment]
@maxmantz I have integrated the redux-oidc lib in my react project. It works well.

Is there any Jest sample test cases for mocking the userManager and related components and other methods in react app. I wanna add test cases for authentication. I didn't find any samples for this. Any links would be appreciated.
