### ISSUE TITLE
Is OidcProvider providing anything?

### ISSUE THREAD

**Issue by jonaskello** [maxmantz/redux-oidc#82]
I would expect `<OidcProvider>` to provide something on the context. I think it did in previous versions. It seems like now it is only listening to the oidc-client and dispatching actions. If that is the case, perhaps a name change would make it more clear. Something like `<OidcListener>`?

**Comment by maxmantz** [comment]
You're right. As far as providing goes, it provides the functionality to fully integrate the user manager with redux by registering the listeners. The name was inspired by redux's provider, which describes that it is a component registered at the root of the app. A change to OidcListener may be more precise in describing its actions, but it has been called `OidcProvider` since the dawn of time and I don't want to break the API because of this. Thanks for the suggestion though.

**Comment by jonaskello** [comment]
Thats OK, I was mostly wondering if it was supposed to put anything on the context. Thanks for the clarification!
