### ISSUE TITLE
Trouble Implementing SSR

### ISSUE THREAD

**Issue by AleksandrAlbert** [maxmantz/redux-oidc#87]
Hey, I see this is an issue that has come up a number of times. I am trying to implement SSR, starting with the aspnet react-redux spa template. When rendering on the server with the default setup i get the following error:

>NodeInvocationException: Prerendering failed because of error: ReferenceError: sessionStorage is not defined

I then tried switching to local storage using the following code:

    import { InMemoryWebStorage } from "oidc-client-fetch";

    export class LocalWebStorage implements InMemoryWebStorage {
        private _data: any;
    
        constructor() {
            this._data = {};
        }
  
        getItem(key : string) {
            return this._data[key];
        }
  
        setItem(key: string, value: any) {
            this._data[key] = value;
        }
  
        removeItem(key: string) {
            delete this._data[key];
        }
  
        get length() {
            return Object.getOwnPropertyNames(this._data).length;
        }
  
        key(index: any) {
            return Object.getOwnPropertyNames(this._data)[index];
        }
    }

And changing my userManagerSettings

```
const userManagerConfig = {
    authority: "http://localhost:5000",
    client_id: "altaonline",
    redirect_uri: "http://localhost:5002/callback.html",
    response_type: "id_token token",
    scope: "openid profile altaonlineapi",
    post_logout_redirect_uri: "http://localhost:5002/index.html",    
    silent_redirect_uri: "http://localhost:5002/silent_renew.html",
    automaticSilentRenew: true,
    filterProtocolClaims: true,
    loadUserInfo: true,
    userStore: new WebStorageStateStore({ store: LocalWebStorage })
};

```

But this only leads to this error:

>NodeInvocationException: Prerendering failed because of error: ReferenceError: localStorage is not defined

Has anyone been able to get this working?

**Comment by maxmantz** [comment]
The issue here is that the `userManager` needs access to a storage mechanism for storing the user info. By default, the `userManager` uses `sessionStorage`. But both `sessionStorage` and `localStorage` are not available on the server. You will need to implement a storage interface for the `userManager` to use. The option can be found [here](https://github.com/IdentityModel/oidc-client-js/wiki#other-optional-settings) in oidc-client wiki (under userStore). Please consult the oidc-client wiki and issue tracker on how to implement this.

**Comment by blerimj** [comment]
@AleksandrAlbert Have you been able to get redux-oidc working on a SSR scenario?
