### ISSUE TITLE
User Logged out is calling even if the user is found.

### ISSUE THREAD

**Issue by cstpraveen** [maxmantz/redux-oidc#90]
![image](https://user-images.githubusercontent.com/5960611/34973193-74852c62-faac-11e7-95ed-0125ee3b7aaa.png)

Whenever the token expires again the user logged out is calling. Someone help me to findout the issue.

```
const oidcMiddleware = createOidcMiddleware(userManager, () => true, false, '/silent_renew/');
  const store = createStore(
    reducer,
    applyMiddleware(oidcMiddleware, ...middleware)
  );

ReactDOM.render(
    Provider store={store}
        OidcProvider store={store} userManager={userManager}
            RouteComponent
        /OidcProvider
    /Provider, document.getElementById("root")
);
registerServiceWorker();

export default store;
```

**Comment by maxmantz** [comment]
This should not happen. From your config however I cannot find out what is wrong. 

But I can see that you have silent renew set up. Please try setting up the store without the middleware and use the `loadUser` helper instead and see if it helps.

**Comment by Andrew-Tan** [comment]
Hi @maxmantz, 

I'm setting up the store with loadUser instead of the middleware, but I'm facing the exact same problem. 

In addition, even if I just sign in, if I open a new browser tab and load the site, the user info also won't properly load. The console output suggest redux-oidc thinks the user info has expired (redux-oidc/USER_EXPIRED).

**Comment by maxmantz** [comment]
@Andrew-Tan This can be caused by the OIDC server returning invalid user data. I cannot diagnose the issue from the information I have.

**Comment by Andrew-Tan** [comment]
Hi @maxmantz,

I think so, as when I test my config on the example app, the same thing happened. Could you help me to debug this?

To allow you to emulate my environment, I'll give you my dev auth server config and test account:
const userManagerConfig = {
  client_id: 'test-dev',
  redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/callback`,
  response_type: 'token id_token',
  scope: 'openid profile offline_access',
  authority: 'https://accounts.open-to-all.com/auth/realms/OpenToAll',
  silent_redirect_uri: `${window.location.protocol}//${window.location.hostname}${window.location.port ? `:${window.location.port}` : ''}/silent_renew`,
  automaticSilentRenew: true,
  filterProtocolClaims: true,
  loadUserInfo: true,
};
(redir URI is set to: https://localhost:8080/*)

Test user:
Username: example@example.com
Password: secret

Thank you in advance for your help!!

**Comment by maxmantz** [comment]
Ah I can see a problem! The redirect URI needs to be set to the URI where your `<CallbackComponent />` is registered at. It looks like it is set to the base URL at the moment. IT should be changed to something like `https://localhost:8080/callback`. See if this helps!

**Comment by Andrew-Tan** [comment]
@maxmantz This part is fine, I set the server to allow callback URI to be any path with the base URI localhost:8080, and I'm already able to login.

The issue is: In Chrome, after being logged in for a few seconds, I was automatically logged out, with redux-oidc/USER_SIGNED_OUT shown in console.

**Comment by Andrew-Tan** [comment]
@maxmantz so I've tried setting the server side to match the redirect URI on the client side, but it didn't help. Besides, the auto sign out issue doesn't appear in Safari, but does for Chrome.

**Comment by maxmantz** [comment]
Happy to hear that you got it working!

**Comment by cstpraveen** [comment]
So if I follow the example, will it work?

**Comment by wildcart** [comment]
@Andrew-Tan Hi, I am having exactly the same issue with a small difference (also trying to authenticate a keycloak server): accessing the page from a different URL doesn't help (even tried different severs, localhost running `npm run dev` and deployed to an actual apache). The  problem also occurs in Firefox (I test FF50, and FF56).

I pretty much took the  `redux-oidc-example` example and replaced the relevant configuration in `userManager.js` by my keycloak configuration (and I stripped out the google related code from `mainPage.js`). 

The result is: authentication works well and I am being re-routed to `mainPage.js` showing my (user) name. After about four second I am being logged out.

In the browser console I see the following 'call-trace' (which is pretty much identical to the one in your screenshot): 
```
store.js:16 Action type: redux-oidc/LOADING_USER
store.js:17 Action payload: undefined
store.js:18 State before: {routing: {…}, oidc: {…}, subscriptions: {…}}
store.js:20 State after: {routing: {…}, oidc: {…}, subscriptions: {…}}
store.js:16 Action type: @@router/LOCATION_CHANGE
store.js:17 Action payload: {pathname: "/", search: "", hash: "", state: null, action: "POP", …}
store.js:18 State before: {routing: {…}, oidc: {…}, subscriptions: {…}}
store.js:20 State after: {routing: {…}, oidc: {…}, subscriptions: {…}}
----------> this is printed four seconds later when I am being logged out <----------
store.js:16 Action type: redux-oidc/USER_EXPIRED
store.js:17 Action payload: undefined
store.js:18 State before: {routing: {…}, oidc: {…}, subscriptions: {…}}
store.js:20 State after: {routing: {…}, oidc: {…}, subscriptions: {…}}
```

Are there any additional things you did to get this to work, except not using 'localhost' to access your dev page / server? 
Are there any specific setting that  I need to configure in keycloak?

Thanks for any feedback.

**Comment by Andrew-Tan** [comment]
Hi @wildcart 
The output does seems different from mine. Because in my case, it's being logged out, but the session isn't expires. 

First, I would recommend you checking if the keycloak cookies are properly set. Maybe try deleting all cookies and authenticate again to see if those deleted cookies appears again. If it doesn't , then there might be some other factors that prevent saving cookie.

If it's set properly, try checking realm settings on keycloak to see if the access token life time is too short (5mins is keycloak default).

Also you should check if automatic renew is working properly. This could be a problem from either keycloak settings or your code. One of ideas I have is try adding offline_access to your scope when setting up oidc clients.

**Comment by wildcart** [comment]
Hi @Andrew-Tan, thanks for the quick reply and pointing out the 'expired' vs 'logout' difference. 

I completely wiped my keycloak installation (drop database and all) and updated to the newest version keycloak (4.0.0-beta1). I then re-created the realm, with exactly the same settings as before and the problem is now fixed to a certain degree: 
```
  Firefox 59             okay
  Chromium 55             okay [1]
  Vivaldi (Chromium 60)  automatic log-out (if app is run in webpack-dev-server, accessed from localhost)
  Vivaldi (Chromium 60)  okay (if app is deployed to same domain serving keycloak).
  Chromium 68            okay
```
[1] if webpack-dev server is set to use http only, for https I get a NET::ERR_CERT_DATE_INVALID violation and cannot open the page because chromium thinks my clock is screwed (ntp UTC though)

This more or less confirms your findings from above, except that current nightly builds of Chromium don't seem to haven any problems setting cookies for localhost.

Why I got an 'expired user' before in all browser even when I deployed the app to an apache serving a 'real' domain, I cannot say.

In the meantime, I figured out that we actually had the same problem in our 'full app' using the `keycloak-js` adapter (which we are now trying to replace by `redux-orcid`). We could solve the problem by disabling the `checkLoginIframe` option:
```
kc.init({onLoad: 'check-sso', checkLoginIframe: false })
    .success(() => { resolve(kc.authenticated)} )
    .error((error) => { reject(error) }
);
```
Do you by any chance have an idea if it is possible to pass the 'checkLoginIfram' option to keycloak via `redux-oidc`?


So login seems to be 'solved' now, but I now have another issue with the `redux-oidc-example`: when I invalidate all sessions from within keycloak (realm -> sessions -> logout all) I expect the app to show the login screen once reloaded. This, however, is not the case. Doing the same in our 'full app' using the `keycloak-js` adapter works as expected. 

Is this something that is not implemented in the example or is there still something wrong in my set-up?


Thanks again
  Christian.

**Comment by wildcart** [comment]
Sorry, for posting again, but I didn't want to change the above comment!

I just figured out what is causing the problem (in chromium): It's the option **Block third-party cookies** in 'Advanced settings -> Content Settings -> Cookies'. When enabled, users are being logged out a few seconds after login. I did the following quick tests with **Block third-party cookies**  enabled:
 * keycloak hosted at *sub.domain.tld*; app run in webpack-dev-server accessed from localhost --> logout
 * keycloak hosted at *sub.domain.tld*; app hosted at sub2.domain.tld --> okay

However, I cannot currently test what happens if the app is deployed at *sub.otherdomain.tld*.

Also, enabling *Block third-party cookies* causes `Action type: redux-oidc/USER_SIGNED_OUT` and not the `Action type: redux-oidc/USER_EXPIRED` I initially got!?

best
  Christian.

**Comment by wildcart** [comment]
I finally got a chance to test keycloak running on a different domain than the app with *Block third-party cookies* enabled: 
* keycloak hosted at sub.domain.tld; app hosted at sub.other.tld --> logout

This is potentially a really big problem, as it will prevent the authentication / app from working properly if an IDP chooses to embed a 'Session Status iframe' and the *Block third-party cookies* option is enabled in chromium based browsers. 

I don't haven any experience with other user management servers like keycloak but to my knowledge this frame is part of the OpenID Connect (Session) specification, and, therefore, other IDPs may or may not be affected as well.

@Andrew-Tan 
Do you have any idea if it is possible to pass the 'checkLoginIfram' option to keycloak using (redux)-oidc (or do you know if this can be disabled in keycloak?).

thnx 
  Christian.

**Comment by Andrew-Tan** [comment]
@wildcart Sorry I don't know if there's any way to disable it. Plus, I think if you disable it, keycloak will lose the ability to check for session status and log users out when you revoke their access.

There's a similar issue for another app as well, and people is discussing about the tradeoff: https://github.com/akvo/akvo-lumen/issues/732

But if disabling the OpenID's status check iframe is the best solution for now. Then maybe @maxmantz know the answer, which is if we can prevent the redux-oidc client from setting the session check iframe.
