### ISSUE TITLE
"redux-oidc/USER_EXPIRED" after "persist/REHYDRATE" in new tab

### ISSUE THREAD

**Issue by yoieh** [maxmantz/redux-oidc#99]
# My setup

I Have followd the [example](https://github.com/maxmantz/redux-oidc-example) to implement this with a reactjs webapplication. I'm using redux with [redux-persist](https://github.com/rt2zz/redux-persist) to persist and rehydrate my store for offline storage and ment to keep users logged in with in the webapp. 

Im not using the middleware do to more issues

## Configure store

**/redux/config/index.js**
```js
import createHistory from "history/createBrowserHistory";

import configureMiddleware from "./configureMiddleware";
import configurePersist, { persistConfig } from "./configurePersist";
import configureReducers from "./configureReducer";
import configureStore from "./configureStore";
import configureSaga, { sagaMiddleware } from "./configureSaga";
import configureMiddleware, { userManager } from "./configureUserManager";
import { initializeState } from "../modules";
import { rootSaga } from "../sagas";
import { loadUser } from "redux-oidc";

export const configure = () => {
  try {
    const reducer = configureReducers(persistConfig);
    const history = createHistory();
    // const { userManager, oidcMiddleware } = configureUserManager();
    const { middleware } = configureMiddleware(
      history,
      sagaMiddleware,
      // oidcMiddleware
    );
    const { store } = configureStore(initializeState, reducer, middleware);
    const { persistor } = configurePersist(store, () => {
      configureSaga(rootSaga);
      loadUser(store, userManager); // <===== loading user after "persist/REHYDRATE"
    });

    return { reducer, history, middleware, store, persistor, userManager };
  } catch (error) {
    console.error(error);
  }
};
```

**/redux/config/configureReducer.js**
```js
import { persistCombineReducers } from "redux-persist";

import { routerReducer } from "react-router-redux";
import { localeReducer } from "react-localize-redux";
import { reducer as oidcReducer } from 'redux-oidc';

import { appReducer } from "../modules";

export default (config, injectedreducer: any) => {
	return persistCombineReducers(config, {
		router: routerReducer,
		locale: localeReducer,
		oidc: oidcReducer,
		app: appReducer,
		...injectedreducer
	});
};
```
**/redux/config/configurePersist.js**
```js
import { persistStore, persistReducer} from "redux-persist";

import localforage from 'localforage'

export const persistConfig = {
	key: "root",
	storage: localforage
};

export default (store: any, doneCallback) => {
    const persistor = persistStore(store, null, doneCallback);
    return { persistor }
};
```

**/redux/config/configureUserManager.js**
```js
import createOidcMiddleware, { createUserManager } from "redux-oidc";

const config = {
....
};

export const userManager = createUserManager(config);

export default () => {
  const oidcMiddleware = createOidcMiddleware(userManager);
  
  return { userManager, oidcMiddleware };
};
```

**/index.js**
```js
import React from "react";
import ReactDOM from "react-dom";

import { Provider } from "react-redux";

import { PersistGate } from "redux-persist/es/integration/react";

import { ConnectedRouter } from "react-router-redux";

import { configure } from "./redux/config";

import { OidcProvider } from "redux-oidc";

import App from "./App";
import registerServiceWorker from "./registerServiceWorker";

import services from "./services";

import "./scss/style.scss";
import "./index.css";

let { history, store, persistor, userManager } = configure();

ReactDOM.render(
  <Provider store={store}>
    <OidcProvider store={store} userManager={userManager}>
      <PersistGate loading={null} persistor={persistor}>
        {/* ConnectedRouter will use the Store from Provider automatically */}
        <ConnectedRouter history={history}>
          <App store={store} />
        </ConnectedRouter>
      </PersistGate>
    </OidcProvider>
  </Provider>,
  document.getElementById("root")
);
registerServiceWorker();
```

**/package.js**
```json
{
....
    "react": "16.0.0",
    "redux": "^3.7.2",
    "redux-persist": "^5.9.1",
    "redux-oidc": "^3.0.0-beta.16",
....
}
```

# My Issue
My login works fine and refresh page after login with works too.

![refresh after after login](https://user-images.githubusercontent.com/5743837/38378044-d135a976-38fc-11e8-9aa3-1b786f86e884.png)

But in a new tab or if I close and open my browser again I can see the rehydrate working setting the old sate of oidc with `user`, `access_token`, `expires_at` and more. But it fails after loding user do to "redux-oidc/USER_EXPIRED" and sets user to `null`. 

![new tab](https://user-images.githubusercontent.com/5743837/38378272-682e824e-38fd-11e8-84d8-710b293d6b42.png)

The `expires_at` is set to one hour after granted access token and I know in fact that i has not expierd do to its the same `expires_at` as the other tab and it has not gone one hour beetween tab switching.

# Question
Why whould this happen and/or am I misunderstanding somthing?

**Comment by yoieh** [comment]
After reading your i see that `loadUser` just uses `getUser()` from oidc-client:s user manager instead of getting it from redux store. Thats probobly why. But dosent that lose the whole purpose of saving it to redux store? Im closing this one its not a bug just a undeveloped feature.

Closes#99

**Comment by maxmantz** [comment]
When the app is initially loaded, the `user` is undefined and the redux store is (usually) empty. By 'usually', I mean when the redux store is in-memory only. This is why we need the `loadUser` helper. I guess if you are using `redux-persist`, that you propably won't need to use `loadUser` to load the user info. 

My guess is that when `loadUser` is called, the `userManager` tries to find user data in `sessionStorage`. Since it can't find any valid user data there, `USER_EXPIRED` is dispatched. Try your config without `loadUser` and see if it helps.

**Comment by maxmantz** [comment]
Any updates on this?

**Comment by yoieh** [comment]
yes sorry it work

**Comment by maxmantz** [comment]
Your setup with `redux-persist` and `localforage` is interesting and something I haven't encountered before so I can't offer a definitive solution for your issue. However I hope to be able to give you a few pointers on where to look for possible solutions.

The most likely cause I see is that the `userManager` uses `sessionStorage` by default to store the user data (including the access token). Since `sessionStorage` is only active for a single tab, it explains why you need to log in again when you open a new tab. Luckily oidc-client offers settings for the [user store](https://github.com/IdentityModel/oidc-client-js/wiki#other-optional-settings) where other storage mechanisms can be attached. Maybe implementing the user store to use `localforage` can solve the issue.

The `loadUser` helper function is used, as I've previously stated, to load existing user data to the store. When it is run right [after the redux-store is created](https://github.com/maxmantz/redux-oidc-example/blob/master/src/store.js#L30), it makes sure that existing user data is available to the app on startup and you don't have to worry about coming up with a manual solution. I'm faily confident that if you can configure the `userManager` to use `localforage`, the issue will get resolved. Best of luck!

**Comment by maxmantz** [comment]
I'll close this for now. Feel free to comment if the issue persists.
